In [1]:
# IPython extension to reload modules before executing user code.
%load_ext autoreload
%autoreload 2 

import numpy as np
import pandas as pd  
from IPython.display import display
import my_functions as mf

In [ ]:
global_disaster_df = pd.read_excel('public_emdat_custom_request_2026-05-04_a356e3df-4aa4-4846-9a37-ed0bcc688498.xlsx')
earthquake_df = pd.read_csv('Earthquakes 2000 2025.csv')

In [3]:
global_disaster_df = mf.standardize_columns(global_disaster_df)
earthquake_df = mf.standardize_columns(earthquake_df)

In [4]:
mf.first_glace(global_disaster_df)

This Dataset has 27608 rows, and 47 columns
=============================================

first glace of the Dataset:

,disno.,historic,classification_key,disaster_group,disaster_subgroup,disaster_type,disaster_subtype,external_ids,event_name,iso,...,"reconstruction_costs,_adjusted_('000_us$)",insured_damage_('000_us$),"insured_damage,_adjusted_('000_us$)",total_damage_('000_us$),"total_damage,_adjusted_('000_us$)",cpi,admin_units,gadm_admin_units,entry_date,last_update
0,1900-0003-USA,Yes,nat-met-sto-tro,Natural,Meteorological,Storm,Tropical cyclone,NaN,NaN,USA,...,NaN,NaN,NaN,30000.0,1131126.0,2.652223,NaN,NaN,2004-10-18,2023-10-17
1,1900-0005-USA,Yes,tec-ind-fir-fir,Technological,Industrial accident,Fire (Industrial),Fire (Industrial),NaN,NaN,USA,...,NaN,NaN,NaN,NaN,NaN,2.652223,NaN,NaN,2003-07-01,2023-09-25
2,1900-0006-JAM,Yes,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),NaN,NaN,JAM,...,NaN,NaN,NaN,NaN,NaN,2.652223,NaN,NaN,2003-07-01,2023-09-25
3,1900-0007-JAM,Yes,nat-bio-epi-vir,Natural,Biological,Epidemic,Viral disease,NaN,Gastroenteritis,JAM,...,NaN,NaN,NaN,NaN,NaN,2.652223,NaN,NaN,2003-07-01,2023-09-25
4,1900-0008-JPN,Yes,nat-geo-vol-ash,Natural,Geophysical,Volcanic activity,Ash fall,NaN,NaN,JPN,...,NaN,NaN,NaN,NaN,NaN,2.652223,NaN,NaN,2003-07-01,2023-09-25

=============================================

Type of data:

disno.                                           str
historic                                         str
classification_key                               str
disaster_group                                   str
disaster_subgroup                                str
disaster_type                                    str
disaster_subtype                                 str
external_ids                                     str
event_name                                       str
iso                                              str
country                                          str
subregion                                        str
region                                           str
location                                         str
origin                                           str
associated_types                                 str
ofda/bha_response                                str
appeal                                           str
declaration                                      str
aid_contribution_('000_us$)                  float64
magnitude                                    float64
magnitude_scale                                  str
latitude                                     float64
longitude                                    float64
river_basin                                      str
start_year                                     int64
start_month                                  float64
start_day                                    float64
end_year                                       int64
end_month                                    float64
end_day                                      float64
total_deaths                                 float64
no._injured                                  float64
no._affected                                 float64
no._homeless                                 float64
total_affected                               float64
reconstruction_costs_('000_us$)              float64
reconstruction_costs,_adjusted_('000_us$)    float64
insured_damage_('000_us$)                    float64
insured_damage,_adjusted_('000_us$)          float64
total_damage_('000_us$)                      float64
total_damage,_adjusted_('000_us$)            float64
cpi                                          float64
admin_units                                      str
gadm_admin_units                                 str
entry_date                                       str
last_update                                      str
dtype: object
=============================================

In [5]:
mf.first_glace(earthquake_df)

This Dataset has 46419 rows, and 10 columns
=============================================

first glace of the Dataset:

,disaster_type,date,latitude,longitude,magnitude,depth_km,location,country,deaths,source
0,Earthquake,2000-01-01,36.874,69.947,5.1,54.3,"29 km SSE of Rust?q, Afghanistan",NaN,NaN,USGS
1,Earthquake,2000-01-01,-60.722,153.670,6.0,10.0,west of Macquarie Island,NaN,NaN,USGS
2,Earthquake,2000-01-01,23.112,143.644,5.2,33.0,"Volcano Islands, Japan region",NaN,NaN,USGS
3,Earthquake,2000-01-02,27.559,92.498,5.0,33.0,"33 km NNE of Bomdila, India",NaN,NaN,USGS
4,Earthquake,2000-01-02,-17.943,-178.476,5.5,582.3,"234 km E of Levuka, Fiji",NaN,NaN,USGS

=============================================

Type of data:

disaster_type        str
date                 str
latitude         float64
longitude        float64
magnitude        float64
depth_km         float64
location             str
country          float64
deaths           float64
source               str
dtype: object
=============================================

In [6]:
global_disaster_df['date'] = mf.normalize_dates(global_disaster_df,'start_year','start_month','start_day')
earthquake_df['date'] = pd.to_datetime(earthquake_df['date'])

In [7]:
global_disaster_df = global_disaster_df.drop(columns=['disno.', 'historic', 'classification_key',
                    'start_year','start_month','start_day',
                    'end_year','end_month','end_day',
                    'entry_date','last_update','admin_units',
                    'ofda/bha_response','external_ids','gadm_admin_units',
                    'reconstruction_costs_(\'000_us$)', 'reconstruction_costs,_adjusted_(\'000_us$)', 'insured_damage_(\'000_us$)', 
                    'insured_damage,_adjusted_(\'000_us$)', 'insured_damage,_adjusted_(\'000_us$)','total_damage,_adjusted_(\'000_us$)',
                    'aid_contribution_(\'000_us$)','river_basin'])
earthquake_df = earthquake_df.drop(columns=['source','country','deaths'])

In [8]:
mf.examine_data(global_disaster_df)

Number of unique values:

disaster_group                 2
disaster_subgroup              9
disaster_type                 32
disaster_subtype              67
event_name                  3779
iso                          231
country                      231
subregion                     17
region                         5
location                   21378
origin                       902
associated_types             149
appeal                         2
declaration                    2
magnitude                   1930
magnitude_scale                6
latitude                    2423
longitude                   2496
total_deaths                 976
no._injured                  939
no._affected                4196
no._homeless                 989
total_affected              6007
total_damage_('000_us$)     1711
cpi                          113
date                       13010
dtype: int64
=============================================

Number of null values:

disaster_group                 0
disaster_subgroup              0
disaster_type                  0
disaster_subtype               0
event_name                 18833
iso                            0
country                        0
subregion                      0
region                         0
location                    2470
origin                     22701
associated_types           23218
appeal                         0
declaration                    0
magnitude                  22266
magnitude_scale            10277
latitude                   24773
longitude                  24773
total_deaths                5566
no._injured                18423
no._affected               15976
no._homeless               24871
total_affected              8956
total_damage_('000_us$)    21607
cpi                          662
date                        3944
dtype: int64
=============================================

Number of duplicated rows:

1
=============================================

In [9]:
mf.examine_data(earthquake_df)

Number of unique values:

disaster_type        1
date              9259
latitude         42097
longitude        43108
magnitude          103
depth_km          9929
location         28861
dtype: int64
=============================================

Number of null values:

disaster_type    0
date             0
latitude         0
longitude        0
magnitude        0
depth_km         0
location         0
dtype: int64
=============================================

Number of duplicated rows:

3
=============================================

In [10]:
mf.descriptive_statistics(global_disaster_df)

Descriptive statistics for numerical variables:

,count,mean,min,25%,50%,75%,max,std
magnitude,5342.0,45343.615014,-57.0,7.0,146.0,5000.0,40000000.0,598659.529099
latitude,2835.0,18.734458,-72.64,3.295,23.2,36.7445,67.93,21.627178
longitude,2835.0,39.722527,-178.252,-0.1,49.414,102.8235,179.65,77.309094
total_deaths,22042.0,1506.346203,1.0,10.0,20.0,47.0,3700000.0,49387.532114
no._injured,9185.0,1312.837888,1.0,12.0,30.0,100.0,1800000.0,22709.351619
no._affected,11632.0,757876.78456,1.0,881.75,7778.0,75000.0,330000000.0,7675867.779941
no._homeless,2737.0,67603.485934,1.0,500.0,2755.0,15000.0,15850000.0,494316.202165
total_affected,18652.0,483203.512492,1.0,70.0,1380.0,22203.25,330000000.0,6129552.64112
total_damage_('000_us$),6001.0,819943.928332,1.0,8900.0,60000.0,345000.0,210000000.0,4976281.913874
cpi,26946.0,56.771008,2.652223,43.416157,58.643553,74.263729,100.0,23.207622
date,23664,2001-11-28 22:53:51.237322,1900-01-06 00:00:00,1994-08-21 00:00:00,2004-12-10 00:00:00,2014-12-16 00:00:00,2026-04-27 00:00:00,NaN

=============================================

Descriptive statistics for categorical variables:

                   count unique                            top   freq
disaster_group     27608      2                        Natural  17818
disaster_subgroup  27608      9                   Hydrological   7060
disaster_type      27608     32                          Flood   6188
disaster_subtype   27608     67                           Road   3014
event_name          8775   3779                        Cholera    515
iso                27608    231                            CHN   2039
country            27608    231                          China   2039
subregion          27608     17             Sub-Saharan Africa   4897
region             27608      5                           Asia  11378
location           25138  21378                          North     67
origin              4907    902                    Heavy rains   1962
associated_types    4390    149  Slide (land, mud, snow, rock)   1303
appeal             27608      2                             No  27375
declaration        27608      2                             No  26394
magnitude_scale    17331      6                            Km2   7508

=============================================

In [11]:
mf.descriptive_statistics(earthquake_df)

Descriptive statistics for numerical variables:

,count,mean,min,25%,50%,75%,max,std
date,46419,2013-03-13 19:09:17.694047,2000-01-01 00:00:00,2007-04-20 00:00:00,2012-07-10 00:00:00,2019-07-05 00:00:00,2025-12-30 00:00:00,NaN
latitude,46419.0,-0.659067,-77.08,-20.78105,-4.4346,21.765,87.386,30.340172
longitude,46419.0,39.018106,-179.997,-72.5385,96.9811,143.131,180.0,122.703712
magnitude,46419.0,5.346322,5.0,5.1,5.2,5.5,9.1,0.410114
depth_km,46419.0,54.922765,-1.77,10.0,23.58,46.2,691.6,101.732054

=============================================

Descriptive statistics for categorical variables:

               count unique                            top   freq
disaster_type  46419      1                     Earthquake  46419
location       46419  28861  South Sandwich Islands region   1424

=============================================

In [12]:
import pandas as pd
import geopandas as gpd

# 1. Crear GeoDataFrames
gdf_disaster = gpd.GeoDataFrame(global_disaster_df, 
                                 geometry=gpd.points_from_xy(global_disaster_df.longitude, global_disaster_df.latitude), 
                                 crs="EPSG:4326")
gdf_earthquake = gpd.GeoDataFrame(earthquake_df, 
                                   geometry=gpd.points_from_xy(earthquake_df.longitude, earthquake_df.latitude), 
                                   crs="EPSG:4326")

# 2. Proyectar a metros (EPSG:3857) para usar el radio de 50km
gdf_disaster_m = gdf_disaster.to_crs(epsg=3857)
gdf_earthquake_m = gdf_earthquake.to_crs(epsg=3857)

# 3. Crear buffer de 50km en la tabla maestra
gdf_disaster_m['geometry'] = gdf_disaster_m.geometry.buffer(50000)

# 4. Unión espacial
# Esto genera un DataFrame con las columnas de ambos, sufijadas con _left y _right
coincidencias = gpd.sjoin(gdf_earthquake_m, gdf_disaster_m, how='inner', predicate='within')

# 5. FILTRO TEMPORAL: Comparar solo el día (ignora horas/minutos)
# .dt.date extrae la fecha pura de los objetos datetime
duplicados_reales = coincidencias[
    coincidencias['date_left'].dt.date == coincidencias['date_right'].dt.date
]

# 6. Identificar y excluir los duplicados de la tabla de terremotos
# Usamos .index para saber qué filas de earthquake_df "cayeron" en el filtro anterior
earthquake_df_solo_nuevos = earthquake_df[~earthquake_df.index.isin(duplicados_reales.index)]

# 7. Unión final
df_final = pd.concat([global_disaster_df, earthquake_df_solo_nuevos], ignore_index=True)

print(f"Total original global_disaster: {len(global_disaster_df)}")
print(f"Sismos de la segunda tabla descartados por proximidad y misma fecha: {len(duplicados_reales.index.unique())}")
print(f"Total final combinado: {len(df_final)}")

Total original global_disaster: 27608
Sismos de la segunda tabla descartados por proximidad y misma fecha: 1188
Total final combinado: 72839

In [13]:
for col in df_final.select_dtypes(include=['object', 'string']).columns:
    df_final[col] = df_final[col].astype(str).replace( np.nan, '')

num_cols = df_final.select_dtypes(include=['float64']).columns
df_final[num_cols] = df_final[num_cols].fillna(0)

In [14]:
# 1. Definimos la máscara: Terremoto Y (faltan datos en country O subregion O region)
mask = (
    (df_final['disaster_type'] == 'Earthquake') &
    (df_final[['latitude', 'longitude']].notnull().all(axis=1)) &
    (df_final['country'] == '') &
    (df_final['subregion'] == '') &
    (df_final['region'] == '')
)

df_a_procesar = df_final[mask].iloc[0:1000].copy()

respuestas = []

for i in range(len(df_a_procesar)):
    row = df_a_procesar.iloc[i]
    res = mf.call_api(row)
    
    if res:
        respuestas.append(res)
    else:
        # En caso de error crítico, rellenamos con valores de error para mantener el índice
        respuestas.append({'country': 'Error', 'subregion': 'Error', 'region': 'Error'})

# 3. Volcar los datos al DataFrame original
if respuestas:
    print(f"Datos obtenidos para {len(respuestas)} filas.")
    res_df = pd.DataFrame(respuestas)
    # Usamos el índice de df_a_procesar para que coincidan las filas exactamente
    res_df.index = df_a_procesar.index
    
    df_final.loc[res_df.index, ['country', 'subregion', 'region']] = res_df[['country', 'subregion', 'region']]

print("Proceso completado.")

Datos obtenidos para 1000 filas.
Proceso completado.

In [15]:
df_final['region'] = df_final['region'].replace({'South America':'Americas', 'North America':'Americas', 'Insular Oceania':'Oceania', 'Central America':'Americas', 'Caribbean':'Americas', 'Southern Asia':'Asia', 'Western Asia':'Asia', 'Eastern Asia':'Asia', 'South-Eastern Asia':'Asia', 'Australian continent':'Oceania'})
condicion = (df_final['disaster_type'] == 'Earthquake') & (df_final['magnitude'].astype(float) == 0)
df_final.loc[condicion, 'magnitude'] = np.nan

In [ ]:
import pymysql
from sqlalchemy import create_engine
from config import user,password,host, bd_name, url


conexion = pymysql.connect(host=host, user=user, password=password)

try:
    with conexion.cursor() as cursor:
        cursor.execute(f"CREATE DATABASE IF NOT EXISTS {bd_name}")
        print(f"Database '{bd_name}' ready.")
finally:
    conexion.close()


engine = create_engine(url)


df_final.to_sql('Natural_disasters', con=engine, if_exists='replace', index=False)

print("Table created succesfully!")

Database 'Natural_disasters' ready.
Table created succesfully!